### ISSUE TITLE
Publish annotations via Maven

### ISSUE THREAD

**Issue by rhwood** [jcip/jcip.github.com#15]
Can you please publish the annotations jar via maven, so it can be used in maven-based projects or recommend which of the existing published versions at [Maven Central](http://search.maven.org/#search%7Cga%7C1%7Cfc%3Anet.jcip.annotations) should be used?

**Comment by Tembrel** [comment]
Is this not sufficient? (It's what I use.)
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>net.jcip</groupId>
  <artifactId>jcip-annotations</artifactId>
  <packaging>jar</packaging>
  <version>1.0</version>
  <name>"Java Concurrency in Practice" book annotations</name>
  <url>http://jcip.net/</url>
 
</project>
```

**Comment by rhwood** [comment]
That works, thanks. A search for ```net.jcip.annotations``` (the package name) buries your package off the first page. Sorry about not searching past the first page.
