### ISSUE TITLE
The label change for the project

### ISSUE THREAD

**Issue by bmkmanoj** [jcip/jcip.github.com#4]
This is not an issue - just a change in label for the project. It is tagged to "Javascript project" - shouldnt it be tagged as a "Java project" ?

![screen shot 2015-05-14 at 2 51 34 pm](https://cloud.githubusercontent.com/assets/715761/7629185/448debdc-fa48-11e4-9563-fede9aab62f0.png)

**Comment by Tembrel** [comment]
I believe that's an automatically-generated tag, because the project is a GitHub pages project, and they use Javascript to generate the pages. There's no Java code being used; what we have is just sample code.

If you know how to change it, re-open and let me know.

**Comment by smallbam** [comment]
I got it.Thank you reply.
regards

從我的 iPhone 傳送
