### ISSUE TITLE
Include license information

### ISSUE THREAD

**Issue by benmccann** [jcip/jcip.github.com#5]
It looks like this work is licensed to the public domain according to http://jcip.net.s3-website-us-east-1.amazonaws.com/listings.html, but it would be nice to confirm that here with the inclusion of a LICENSE file

**Comment by Tembrel** [comment]
Care to make a PR?

**Comment by Tembrel** [comment]
I believe this can be closed as a result of this commit: 04f4a1714a1b5c96c471fa14d97d4118b69ddf95
